# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/encrypting-files/

language: node_js
node_js: '6.11.3'

sudo: false

# S: Build Lifecycle
before_install:
  - export TZ='Asia/Shanghai'
  - openssl aes-256-cbc -K $encrypted_e2774ebf4996_key -iv $encrypted_e2774ebf4996_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - cd themes/next
  - git checkout tags/v5.1.2
  - cd ../../
  - git config --global user.name "liqiang311"
  - git config --global user.email "385098415@qq.com"

#  - npm install hexo-generator-index --save
install:
  - npm install hexo-cli -g
  - npm install

#cache:
#  apt: true   
#  directories:    
#    - node_modules

addons:
  ssh_known_hosts: 
    - github.com
    - git.coding.net

script:
  - hexo clean
  - hexo g
  - hexo d

branches: 
  only: 
  - master