# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/encrypting-files/

language: node_js
node_js: '6.11.3'

cache:
  - apt:true
  - directories:node_modules
  - pandoc
  - hexo-cli
  - hexo-renderer-pandoc

# S: Build Lifecycle
before_install:
  - export TZ='Asia/Shanghai'
  - openssl aes-256-cbc -K $encrypted_e2774ebf4996_key -iv $encrypted_e2774ebf4996_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - git config --global user.name "liqiang311"
  - git config --global user.email "385098415@qq.com"
  - echo "\$main-desktop                     = 90%" >> themes/next/source/css/_variables/custom.styl
  - cat themes/next/source/css/_variables/custom.styl

install:
  - wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
  - sudo dpkg -i pandoc*.deb
  - npm install hexo-cli -g
  - npm install hexo-generator-index --save
  - npm install hexo-generator-sitemap --save
  - npm install hexo-generator-baidu-sitemap --save
  - npm install
  - npm install hexo-renderer-pandoc --save

addons:
  ssh_known_hosts: 
    - github.com
    - git.coding.net

script:
  - hexo clean
  - hexo g

after_script:
  - hexo d

branches: 
  only: 
  - master