language: node_js
node_js: '6.11.3'

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "liqiang311"
  - git config user.email "385098415@qq.com"
  - git add .
  - git commit -m "Travis CI AutoUpdate"
  - git remote add all "https://${GITHUB_TOKEN}@${GITHUB_REF}"
  - git remote set-url --add all "https://${CODING_TOKEN}@${CODING_REF}"
  - git push -f all --all
# E: Build LifeCycle

branches: master
env:
 global:
   - GITHUB_REF: github.com/liqiang311/liqiang311.github.io.git
   - CODING_REF: git.coding.net/liqiang311/liqiang311.git